### ISSUE TITLE
Any reason not using homebrew-core?

### ISSUE THREAD

**Issue by chenrui333** [loadimpact/homebrew-k6#6]
The k6 formula seems pretty easy to maintain in the homebrew-core?

I am asking because I wonder if we can move it to homebrew-core and I can help maintaining it. :)

**Comment by na--** [comment]
Moving this to homebew-core would probably be better, and there's a super-old k6 issue about it: https://github.com/loadimpact/k6/issues/380

I have a few questions, сince I'm not a Mac/homebrew user:
- If we remove this formula after it's in homebrew-core, would any existing k6 users that have installed it automagically get the new k6 versions when we release them? Or would they have to re-install k6 from the new formula?
- How long does it usually take to update a homebrew-core formula when a new version comes out? We usually update this repo as part of the [k6 release process](https://github.com/loadimpact/k6/wiki/Release-Procedure), but I see quite a few open PRs in homebrew-core that are weeks old.
- Does one need to be a Mac/homebrew user in order to submit a pull request for updating a package version in homebrew-core? Looking at the currently open PRs, I can easily create a PR for new k6 versions by hand, but the [contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) only speak in terms of `brew` commands...

**Comment by chenrui333** [comment]
> If we remove this formula after it's in homebrew-core, would any existing k6 users that have installed it automagically get the new k6 versions when we release them? Or would they have to re-install k6 from the new formula?

that is really good question, I do not know, I will cross-post this when I submit the PR for discussion and comments. My guess is it needs to be reinstalled.

> How long does it usually take to update a homebrew-core formula when a new version comes out? We usually update this repo as part of the k6 release process, but I see quite a few open PRs in homebrew-core that are weeks old.

Should be within half day or one day (PR, build, and merge, and then bottle for helping installation).

> Does one need to be a Mac/homebrew user in order to submit a pull request for updating a package version in homebrew-core? Looking at the currently open PRs, I can easily create a PR for new k6 versions by hand, but the contributing guidelines only speak in terms of brew commands...

Yes, everyone can submit PR for keeping refreshed.

**Comment by na--** [comment]
> that is really good question, I do not know, I will cross-post this when I submit the PR for discussion and comments. My guess is it needs to be reinstalled.

If that's the case, for a few months we probably should continue supporting this repo and updating it when new releases come out, even if it's also in homebrew-core. Do you know if there's a way to inject a warning message in the package, so that when users update it they can see that there's a new homebrew-core package for k6?

**Comment by chenrui333** [comment]
Yeah, if that is the case, totally agree with the rollout strategy. :)

**Comment by chenrui333** [comment]
@na-- Filed a PR 🎉

**Comment by na--** [comment]
Merged the PR, will update the k6 README when we tests things a little bit more :slightly_smiling_face: We plan to release k6 v0.25.0 fairly soon, so hopefully there won't be any issues with the migration to homebrew core.
